### ISSUE TITLE
GNOME 3.38 support

### ISSUE THREAD

**Issue by rudrab** [mlutfy/hidetopbar#255]
May be its a bit premature to ask, but its crashing often in gnome 3.38 (fedora 33 prerelase).
I have tried both from gnome-extension and git.

**Comment by BPaden** [comment]
In 3.38 the hot corner is still working when "Keep hot corner sensitive option, even in hidden state" is turned off. Workaround is to install the No Topleft Hot Corner extension.

**Comment by knimer** [comment]
I have the same issue with Gnome 3.38 on Ubuntu 20.10

It works for a while then it stops working and causes an issue by not being able to access the title bar of the open apps windows that is hidden below the no longer hiding top bar.

**Comment by ilelann** [comment]
I have the same setup and I noticed this errors with  `journalctl /usr/bin/gnome-shell`
```
oct. 04 15:26:48 fwing gnome-shell[20840]: JS ERROR: Error: No signal 'allocation-changed' on object 'StBoxLayout'
                                           reallocateTopIcons@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:40:26
                                           onComplete@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:150:21
                                           _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:84:13
                                           _easeActor/<@resource:///org/gnome/shell/ui/environment.js:165:64
```
So I commented out the involved line in reallocateTopIcons.
So far it seems to work but it might be too early to confirm anything.
One thing to note : 
With my hack, it seems you need to re-toggle focus on a recently maximized window to get rid of the top bar.
It does not directly disappear after maximization, but I can live with that.

**Comment by rudrab** [comment]
currently my only problem is it does not survives a `sleep`. I have to do a `logout` to get `hidetopbar` working.

**Comment by pablotron** [comment]
PR #256 should fix the `allocation-changed` error and prevent hidetopbar from randomly crashing in GNOME 3.38.

**Comment by rvlobato** [comment]
@ilelann I think that #256 fixes it, I am getting rid of the top bar right away. With #256 and removing reallocateTopIcons everything works fine in my two machines. Thanks.

**Comment by rudrab** [comment]
I tried #256 manually (I don't know how to apply a PR locally, so just altered the files manually) and installed it from source. Nothing has changed.

**Comment by ilelann** [comment]
#256 does remove the warning I reported but does not seem to fix the "top bar is sticky after sleep" issue.
Here are the logs I have when going to sleep:

```
oct. 05 09:05:19 fwing gnome-shell[3870]: JS ERROR: TypeError: Object 0x3b60372a7a30 is not a subclass of GObject_ParamSpec, it's a GObject_Boxed
                                          reallocateTopIcons@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:41:26
                                          onComplete@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:150:21
                                          _makeEaseCallback/<@resource:///org/gnome/shell/ui/environment.js:84:13
                                          _easeActor/<@resource:///org/gnome/shell/ui/environment.js:165:64
oct. 05 09:05:24 fwing gnome-shell[3870]: Source ID 923 was not found when attempting to remove it
oct. 05 09:05:24 fwing gnome-shell[3870]: JS ERROR: Extension hidetopbar@mathieu.bidon.ca: TypeError: Object 0x3b60372f38b0 is not a subclass of GObject_ParamSpec, it's a GObject_Boxed
                                          reallocateTopIcons@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:41:26
                                          show@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:140:13
                                          destroy@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/panelVisibilityManager.js:451:14
                                          disable@/home/ilelann/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/extension.js:43:16
                                          _callExtensionDisable@resource:///org/gnome/shell/ui/extensionSystem.js:108:32
                                          _disableAllExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:611:22
                                          _disableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:610:52
                                          _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                          _sync@resource:///org/gnome/shell/ui/sessionMode.js:195:14
                                          pushMode@resource:///org/gnome/shell/ui/sessionMode.js:156:14
                                          activate@resource:///org/gnome/shell/ui/screenShield.js:572:34
                                          lock@resource:///org/gnome/shell/ui/screenShield.js:621:14
                                          _prepareForSleep@resource:///org/gnome/shell/ui/screenShield.js:219:22
                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                          _prepareForSleep@resource:///org/gnome/shell/misc/loginManager.js:207:14
                                          _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                          _convertToNativeSignal@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:169:19
oct. 05 09:05:24 fwing gnome-shell[3870]: Could not create transient scope for PID 5048: GDBus.Error:org.freedesktop.DBus.Error.UnixProcessIdUnknown: Process with ID 5048 does not exist.
```

**Comment by ilelann** [comment]
I forgot to mention but the erorrs I reported above (https://github.com/mlutfy/hidetopbar/issues/255#issuecomment-703446284) are with #256 locally applied.

**Comment by terencode** [comment]
I get the `JS ERROR: TypeError: Object 0x209db3e62340 is not a subclass of GObject_ParamSpec, it's a GObject_Boxed` that is mentioned when enabling the extension on 591d601.

**Comment by pablotron** [comment]
Commenting out the call to `Main.panel._rightBox.emit` in
`reallocateTopIcons` fixes this error for me.

* Térence Clastres (notifications@github.com) wrote:
>    I get the JS ERROR: TypeError: Object 0x209db3e62340 is not a subclass of
>    GObject_ParamSpec, it's a GObject_Boxed that is mentioned when enabling
>    the extension on 591d601.
> 
>    —
>    You are receiving this because you commented.
>    Reply to this email directly, view it on GitHub, or unsubscribe.

-- 
Paul Duncan <pabs@pablotron.org>
https://pablotron.org/

**Comment by tuxor1337** [comment]
Thanks for the proposed fix @pablotron - it's in the most recent commit. Does that one work for everyone here?

**Comment by ilelann** [comment]
> Thanks for the proposed fix @pablotron - it's in the most recent commit. Does that one work for everyone here?

It does indeed work for me. It's fine even after a sleep if I comment out the "Main.panel._rightBox.emit" call.
(but still taking the https://github.com/mlutfy/hidetopbar/pull/256/files#diff-9fe2037add1faffdbfaebd929733de5dL162 from #256 , of course)

**Comment by pablotron** [comment]
> Thanks for the proposed fix @pablotron - it's in the most recent commit. Does that one work for everyone here?

Works fine for me as well.

**Comment by tuxor1337** [comment]
Thanks for your feedback! Closing as fixed.

**Comment by rudrab** [comment]
yes! This is working. Thanks a lot.

**Comment by rudrab** [comment]
HI, The gnome-extension center has an updated version with 3.38 support. Does this include this fix?

**Comment by ilelann** [comment]
I upgraded and from what I have in my local files, I'd say it does.

**Comment by ilelann** [comment]
I am not sure it's related to GNOME 3.38 or to recent fixes but I noticed that the top bar clock is frozen, and it is only so when the extension is activated.
"frozen" means : when you press Win key, top bar will display an obsolete past time until you move your mouse cursor on it, which will suddenly refresh the time.

**Comment by coldtobi** [comment]
> I am not sure it's related to GNOME 3.38 or to recent fixes but I noticed that the top bar clock is frozen, and it is only so when the extension is activated.
> "frozen" means : when you press Win key, top bar will display an obsolete past time until you move your mouse cursor on it, which will suddenly refresh the time.

This has been reported as #257.
